neural_network:
  category: "LeNet"
  pretrained: true
  weight: ''
  classes_num: 2

optimizer:
  category: "SGD"
  lr: 0.001

dataset:
  name: "HandWrittenData"
  split_manual: true     # if true, then eval is valid
  train:
    imgs_path: "/home/hozumi/datasets/classify/dogs_cats/train/images"
    map_file: '/home/hozumi/datasets/classify/dogs_cats/train/labels'
    pre_process:
      size:
        --640
         -640

    transform:
      totensor: true

  eval:
    imgs_path: "/home/hozumi/datasets/classify/dogs_cats/eval/images"
    map_file: '/home/hozumi/datasets/classify/dogs_cats/eval/labels'
loss_fn:
  "CrossEntropyLoss"

device:
  'cuda:0'
output:

  ''