neural_network:
  category: "LeNet"
  pretrained: true
  weight: ''
  classes_num: 2

optimizer:
  category: "SGD"
  lr: 0.001

dataset:
  name: "HandWrittenData"
  train:
    imgs_path: "/home/yuki/datasets/classify/dogs_cats/train/images"
    map_file: '/home/yuki/datasets/classify/dogs_cats/train/labels'
    transform:
  eval:
    imgs_path: "/home/yuki/datasets/classify/dogs_cats/eval/images"
    map_file: '/home/yuki/datasets/classify/dogs_cats/eval/labels'
loss_fn:
  "CrossEntropyLoss"

device:
  'cuda:0'
output:

  ''